# Generated by Django 5.0.1 on 2024-01-17 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=155)),
                ('email', models.EmailField(max_length=155)),
                ('secret', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('short_name', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unique_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('shelf_life', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Beauty', 'Beauty'), ('Food', 'Food'), ('Home Appliances', 'Home Appliances'), ('Books', 'Books'), ('Sports & Outdoors', 'Sports Outdoors'), ('Toys', 'Toys'), ('Health & Wellness', 'Health Wellness'), ('Furniture', 'Furniture'), ('Jewelry', 'Jewelry'), ('Automotive', 'Automotive'), ('Pet Supplies', 'Pet Supplies'), ('Electrical Tools', 'Electrical Tools'), ('Music Instruments', 'Music Instruments'), ('Art & Crafts', 'Art Crafts'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Garden & Outdoor', 'Garden Outdoor'), ('Stationery', 'Stationery'), ('Tech Gadgets', 'Tech Gadgets'), ('Fitness Equipment', 'Fitness Equipment'), ('Party Supplies', 'Party Supplies'), ('Software', 'Software'), ('Cameras & Photo', 'Cameras Photo'), ('Baby Products', 'Baby Products'), ('Home Decor', 'Home Decor'), ('Travel Accessories', 'Travel Accessories'), ('Office Products', 'Office Products'), ('Music & Movies', 'Music Movies'), ('Other', 'Other')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufactured', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
