# Generated by Django 5.0.1 on 2024-01-30 07:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_instance_upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.product_upload_path),
        ),
    ]
