# Generated by Django 5.0.1 on 2024-01-30 19:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productinstance_qr_alter_product_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to=core.models.product_upload_path),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='qr',
            field=models.FileField(blank=True, null=True, upload_to=core.models.product_instance_upload_path),
        ),
    ]
